- exercise: Caratterizzazione Ceramica (Thickness)
  image: singleCeramics.png
  settings:
    - name: Ceramica
      id: CeramicsTab
      components:
        - kind: uidropdown
          id: MenuForma
          labels:
            - text: Forma
              position: left
          Items:
            - Quadrato
            - Rettangolo
            - Cerchio 
        - kind: uispinner
          id: CampoParametro1
          labels:
            - text: Placeholder
              position: left
              rules:
                - id: MenuForma
                  value: Quadrato
                  text: Lato
                - id: MenuForma
                  value: Rettangolo
                  text: Base
                - id: MenuForma
                  value: Cerchio
                  text: Raggio
            - text: m
              position: right
          Step: 0.001
          Limits: [0, 1]
        - kind: uispinner
          id: CampoParametro2
          visible_when:
            id: MenuForma
            value: Rettangolo
          labels:
            - text: Altezza
              position: left
            - text: m
              position: right
          Step: 0.001
          Limits: [0, 1]
        - kind: uispinner
          id: CampoSpessore
          labels:
            - text: Spessore
              position: left
            - text: m
              position: right
          Step: 0.001
          Limits: [0, 1]
        - kind: uidropdown
          id: MenuPz
          labels:
            - text: Pz
              position: left
          Items:
            - Pz21
            - Pz23
            - Pz24
            - Pz26
            - Pz27
            - Pz28
            - Pz29
            - Pz34
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz26'
  pipeline:
    - "Zi = ( (1./(1i .* omega .* C0)) .* ( 1 - ( ((h33^2)/(c33*beta33)) .* (2./theta) .* tan(theta./2) ) ) );"
    - "[moduloZi, faseZi] = calcolaModuloEFase(Zi, true, false);"
    - "index_min = (moduloZi == min(moduloZi));"
    - "index_max = (moduloZi == max(moduloZi));"
    - "fmin = f(1,index_min);"
    - "fmax = f(1,index_max);"
    - "Keff = ((fmax^2) - (fmin^2))/(fmax^2);"
  resultText: "['Risultato calcolo fattore di accoppiamento efficace:\n\n\t Keff^2 = ', num2str(Keff)]"
  plots:
    - name: Zin
      drawing:
        - 'stampaGrafici(f, moduloZi, faseZi, "Zin: input impedance", "blue", "Zin");'

  