- name: Ceramica
  id: CeramicsTab
  components:
    - kind: uidropdown
      id: MenuForma
      labels:
        - text: Forma
          position: left
      Items:
        - Quadrato
        - Rettangolo
        - Cerchio 
    - kind: uispinner
      id: CampoParametro1
      labels:
        - text: Placeholder
          position: left
          rules:
            - id: MenuForma
              value: Quadrato
              text: Lato
            - id: MenuForma
              value: Rettangolo
              text: Base
            - id: MenuForma
              value: Cerchio
              text: Raggio
        - text: m
          position: right
      Step: 0.001
      Limits: [0, 1]
    - kind: uispinner
      id: CampoParametro2
      visible_when:
        id: MenuForma
        value: Rettangolo
      labels:
        - text: Altezza
          position: left
        - text: m
          position: right
      Step: 0.001
      Limits: [0, 1]
    - kind: uispinner
      id: CampoSpessore
      labels:
        - text: Spessore
          position: left
        - text: m
          position: right
      Step: 0.001
      Limits: [0, 1]
    - kind: uidropdown
      id: MenuPz
      labels:
        - text: Pz
          position: left
      Items:
        - Pz21
        - Pz23
        - Pz24
        - Pz26
        - Pz27
        - Pz28
        - Pz29
        - Pz34
- name: Strati Meccanici
  id: MaterialiTab
  components:
    - kind: uidropdown
      id: MenuStrati
      labels:
        - text: Masse di precarico
          position: left
      Items:
        - Acciaio inossidabile 347
        - Alluminio 6262-T9
        - Ferro
        - Titanio
        - Tungsteno
    - kind: uidropdown
      id: MenuConcentratore
      labels:
        - text: Concentratore
          position: left
      Items:
        - Acciaio inossidabile 347
        - Alluminio 6262-T9
        - Ferro
        - Titanio
        - Tungsteno
    - kind: uispinner
      id: CampoGuadagno
      labels:
        - text: Guadagno del concentratore
          position: left
      Step: 0.01
      Limits: [1, inf]