- "Zi = ( (1./(1i .* omega .* C0)) .* ( 1 - ( ((h33^2)/(c33*beta33)) .* (2./theta) .* tan(theta./2) ) ) );"
- "[moduloZi, faseZi] = calcolaModuloEFase(Zi, false, true);"
- "index_min = (moduloZi == min(moduloZi));"
- "index_max = (moduloZi == max(moduloZi));"
- "fmin = f(1,index_min);"
- "fmax = f(1,index_max);"
- "Keff = ((fmax^2) - (fmin^2))/(fmax^2);"