- exercise: Caratterizzazione Ceramica (Thickness)
  image: singleCeramics.png
  settings: carat_ceram_thick/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz26'
  pipeline: carat_ceram_thick/pipeline.yaml
  plots:
    - name: Zin
      drawing:
        - 'stampaGrafici(f, moduloZi, faseZi, "Zin: input impedance", "blue", "Zin");'
  resultText: "['Risultato calcolo fattore di accoppiamento efficace:\n\n\t $K_{eff}^2=', num2str(Keff), '$']"
  resultTextInterpreter: 'latex'
- exercise: Modello Terminale (Thickness)
  image: singleCeramics.png
  settings: model_termi_thick/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz26'
    - id: ImpedenzeTab
      values:
        MenuZ1: 'Aria (20°C)'
        MenuZ2: 'Acqua (20°C)'
        CheckMezziStandard: false
  pipeline: model_termi_thick/pipeline.yaml
  plots: model_termi_thick/plots.yaml
  resultText: "['Risultato calcolo fattore di accoppiamento efficace:\n\n\t $', Keff, '$']"
  resultTextInterpreter: 'latex'
- exercise: Modello Terminale (Thickness Coupled)
  image: singleCeramics.png
  settings: model_termi_thick_coupled/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        CampoCoppie: 1
        MenuPz: 'Pz26'
    - id: ImpedenzeTab
      values:
        CheckMezziStandard: false
        MenuZ1: 'Aria (20°C)'
        MenuZ2: 'Acqua (20°C)'
  pipeline: model_termi_thick_coupled/pipeline.yaml
  plots: model_termi_thick_coupled/plots.yaml
  resultText: "['Risultato calcolo fattore di accoppiamento efficace:\n\n\t ', Keff]"
  resultTextInterpreter: 'latex'
- exercise: Progettazione trasduttore banda larga
  image: wideband.png
  settings: trasd_piezo_wideb/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz26'
  pipeline: trasd_piezo_wideb/pipeline.yaml
  plots: trasd_piezo_wideb/plots.yaml
  resultText: "['Banda Frazionaria no backing no plate:\n\n\t -3db: $FBW= ', num2str(FBW_3dB_without_backing_without_plate), '\% %$\t -6db: $FBW= ', num2str(FBW_6dB_without_backing_without_plate), '\%$\n\nBanda Frazionaria con backing no plate:\n\n\t -3db: $FBW= ', num2str(FBW_3dB_with_backing_without_plate), '\%$\n\t -6db: $FBW= ', num2str(FBW_6dB_with_backing_without_plate), '\%$\n\nBanda Frazionaria no backing con plate:\n\n\t -3db: $FBW= ', num2str(FBW_3dB_without_backing_with_plate), '\%$\n\t -6db: $FBW= ', num2str(FBW_6dB_without_backing_with_plate), '\%$\n\nBanda Frazionaria con backing con plate:\n\n\t -3db: $FBW= ', num2str(FBW_3dB_with_backing_with_plate_cached), '\%$\n\t -6db: $FBW= ', num2str(FBW_6dB_with_backing_with_plate), '\%$\n\nLo spessore ottimale è: $l_{plate}=', num2str(l_plate_best_scaled), '\cdot10^{-3}$', '\nLa Banda Frazionaria a -3dB ottimale è: $FBW= ', num2str(FBW_max), '\%$\nSpessore convertito: $', num2str(l_plate_best_previous_scaled), '\cdot10^{-3} \rightarrow ', num2str(l_plate_best_scaled), '\cdot10^{-3}$', '\nBanda Frazionaria a -3dB con backing e plate ottimizzato: $FBW= ', num2str(FBW_3dB_with_backing_with_plate_optimized), '\%$\nBanda Frazionaria a -6dB con backing e plate ottimizzato: $FBW= ', num2str(FBW_6dB_with_backing_with_plate_optimized), '\%$']"
  resultTextInterpreter: 'latex'
- exercise: Progettazione trasduttore ultrasonico (singolo)
  image: langevin.png
  settings: trasd_piezo_ultra_single/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz27'
    - id: MaterialiTab
      values:
        MenuStrati: Acciaio inossidabile 347
  pipeline: trasd_piezo_ultra_single/pipeline.yaml
  plots: trasd_piezo_ultra_single/plots.yaml
- exercise: Progettazione trasduttore ultrasonico (accoppiato)
  image: langevin_coupled.png
  settings: trasd_piezo_ultra_coupled/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz27'
    - id: MaterialiTab
      values:
        MenuStrati: Acciaio inossidabile 347
  pipeline: trasd_piezo_ultra_coupled/pipeline.yaml
  plots: trasd_piezo_ultra_coupled/plots.yaml
- exercise: Progettazione trasduttore ultrasonico con concentratore
  image: concentratore.png
  settings: trasd_piezo_ultra_concentratore/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        MenuPz: 'Pz27'
    - id: MaterialiTab
      values:
        MenuStrati: Acciaio inossidabile 347
        MenuConcentratore: Acciaio inossidabile 347
        CampoGuadagno: 1.5
  pipeline: trasd_piezo_ultra_concentratore/pipeline.yaml
  plots: trasd_piezo_ultra_concentratore/plots.yaml
- exercise: Analizzatore Ceramiche Piezoelettriche
  image: analizzatore.png
  settings: analiz_ceram_piezo/tabSettings.yaml
  defaults:
    - id: CeramicsTab
      values:
        MenuForma: Quadrato
        CampoParametro1: 0.010
        CampoParametro2: 0.010
        CampoSpessore: 0.001
        CampoMassa: 1.0000
    - id: FlowTab
      values:
        CampoFlow: 1
        CampoZiFlow: 1
    - id: ParametriTab
      values:
        CampoC0: 1
        CampoR1: 1
        CampoL1: 1
        CampoC1: 1
  pipeline: analiz_ceram_piezo/pipeline.yaml
  plots: analiz_ceram_piezo/plots.yaml
  resultText: "tableToHtml(T)"
  resultTextInterpreter: 'html'