- name: Zin
  drawing:
    - "stampaGrafici(f, Zin{1}, Zin{2}, 'Comparing Zin without and with a correction with two ceramics', 'blue', 'Zin', 'Zin', ' without a correction');"
    - "stampaGrafici(f, Zin_iter{1}, Zin_iter{2}, 'Comparing Zin without and with a correction with two ceramics', 'orange', 'Zin', 'Zin', ' with a correction');"
- name: FTT
  drawing:
    - "stampaGrafici(f, FTT{1}, FTT{2}, 'Comparing TTF without and with a correction with two ceramics', 'blue', 'TTF', 'TTF', ' without a correction');"
    - "stampaGrafici(f, FTT_iter{1}, FTT_iter{2}, 'Comparing TTF without and with a correction with two ceramics', 'orange', 'TTF', 'TTF', ' with a correction');"